services:
  messenger:
    image: messenger:dev
    build: .
    restart: no
    ports:
      - "8083:8080"
    environment:
      - MSG_DB_URL=jdbc:postgresql://msg_test-postgres-1/messenger_db_dev
      - MONGO_DB_URL=mongodb://admin:password@localhost:27017/filedb?authSource=admin
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=filedb
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:latest
    restart: "no"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/status || exit -1
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5
volumes:
  postgres_data:
  pgadmin_data:
  mongo-data:
    driver: local