openapi: 3.0.1
info:
  title: Snippets API
  description: Test description
  termsOfService: https://www.google.com/policies/terms/
  contact:
    email: contact@snippets.local
  license:
    name: BSD License
  version: v1
servers:
  - url: http://127.0.0.1:8000/
security:
  - Basic: []
paths:
  /messenger/chat/:
    get:
      tags:
        - messenger
      operationId: messenger_chat_list
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                required:
                  - count
                  - results
                type: object
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                    format: uri
                    nullable: true
                  previous:
                    type: string
                    format: uri
                    nullable: true
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/ChatList'
  /messenger/chat/create/:
    post:
      tags:
        - messenger
      operationId: messenger_chat_create_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatCreate'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatCreate'
      x-codegen-request-body-name: data
  /messenger/message/:
    get:
      tags:
        - messenger
      operationId: messenger_message_list
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
  /messenger/message/create/:
    post:
      tags:
        - messenger
      operationId: messenger_message_create_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
      x-codegen-request-body-name: data
  /users/:
    get:
      tags:
        - users
      operationId: users_list
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /users/auth/:
    post:
      tags:
        - users
      description: |-
        Метод POST для аутентификации пользователя.
        Принимает номер телефона и код подтверждения.
        Проверяет наличие пользователя с указанным номером телефона.
        Если пользователь существует и код подтверждения верный,
        генерирует токен доступа и возвращает его в ответе.
        Возвращает ответ с токеном доступа в случае успешной аутентификации,
        или ответ с сообщением об недопустимых учетных данных.
      operationId: users_auth_create
      responses:
        '201':
          description: ''
          content: {}
  /users/token/refresh/:
    post:
      tags:
        - users
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      operationId: users_token_refresh_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
      x-codegen-request-body-name: data
  /users/update/{id}/:
    put:
      tags:
        - users
      operationId: users_update_update
      parameters:
        - name: id
          in: path
          description: A unique integer value identifying this user.
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserUpdate'
      x-codegen-request-body-name: data
    patch:
      tags:
        - users
      operationId: users_update_partial_update
      parameters:
        - name: id
          in: path
          description: A unique integer value identifying this user.
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserUpdate'
      x-codegen-request-body-name: data
  /users/varify/:
    post:
      tags:
        - users
      description: >-
        Метод POST для отправки кода подтверждения.

        Принимает номер телефона, проверяет наличие пользователя с этим номером.

        Если пользователь существует, генерирует 4-х значный код подтверждения
        (otp_code),

        сохраняет его для пользователя в базе данных и имитирует отправку кода
        авторизации.

        Если пользователь не существует, генерирует 4-х значный код
        подтверждения (otp_code),

        создает нового пользователя с указанным номером телефона и сохраняет его
        в базе данных.

        Возвращает ответ с сообщением об успешной отправке кода или создании
        кода.
      operationId: users_varify_create
      responses:
        '201':
          description: ''
          content: {}
  /users/{id}/:
    get:
      tags:
        - users
      operationId: users_read
      parameters:
        - name: id
          in: path
          description: A unique integer value identifying this user.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    ChatList:
      type: object
      properties:
        id:
          title: ID
          type: integer
          readOnly: true
        created:
          title: Время и дата создания чата
          type: string
          format: date-time
          readOnly: true
        creator:
          title: Создатель
          type: integer
          nullable: true
        participants:
          uniqueItems: true
          type: array
          items:
            title: Участники
            type: integer
            nullable: true
    ChatCreate:
      type: object
      properties:
        creator:
          title: Создатель
          type: integer
          nullable: true
    Message:
      required:
        - chat
        - text
      type: object
      properties:
        id:
          title: ID
          type: integer
          readOnly: true
        text:
          title: Текст сообщения
          minLength: 1
          type: string
        attachment:
          title: Attachment
          type: string
          format: uri
          nullable: true
          readOnly: true
        created:
          title: Дата и время создания сообщения
          type: string
          format: date-time
          readOnly: true
        update:
          title: Дата и время редактирования сообщения
          type: string
          format: date-time
          readOnly: true
        sender:
          title: Отправитель
          type: integer
          nullable: true
        chat:
          title: Чат
          type: integer
    User:
      required:
        - first_name
        - last_name
        - nickname
        - otp_code
        - personal_information
        - phone
      type: object
      properties:
        id:
          title: ID
          type: integer
          readOnly: true
        last_login:
          title: Last login
          type: string
          format: date-time
          nullable: true
        is_superuser:
          title: Superuser status
          type: boolean
          description: >-
            Designates that this user has all permissions without explicitly
            assigning them.
          default: false
        email:
          title: Email address
          maxLength: 254
          type: string
          format: email
        is_staff:
          title: Staff status
          type: boolean
          description: Designates whether the user can log into this admin site.
          default: false
        is_active:
          title: Active
          type: boolean
          description: >-
            Designates whether this user should be treated as active. Unselect
            this instead of deleting accounts.
          default: true
        date_joined:
          title: Date joined
          type: string
          format: date-time
        phone:
          title: Номер телефона
          maxLength: 128
          minLength: 1
          type: string
        first_name:
          title: Имя пользователя
          maxLength: 100
          minLength: 1
          type: string
        last_name:
          title: Фамилия пользователя
          maxLength: 100
          minLength: 1
          type: string
        nickname:
          title: Прозвище пользователя
          maxLength: 100
          minLength: 1
          type: string
        personal_information:
          title: Информация о себе
          maxLength: 500
          minLength: 1
          type: string
        avatar:
          title: Аватар
          type: string
          format: uri
          nullable: true
          readOnly: true
        is_verified:
          title: Статус верификации пользователя
          type: boolean
          default: false
        otp_code:
          title: Otp code
          maxLength: 5
          minLength: 1
          type: string
        groups:
          uniqueItems: true
          type: array
          description: >-
            The groups this user belongs to. A user will get all permissions
            granted to each of their groups.
          items:
            type: integer
            description: >-
              The groups this user belongs to. A user will get all permissions
              granted to each of their groups.
        user_permissions:
          uniqueItems: true
          type: array
          description: Specific permissions for this user.
          items:
            type: integer
            description: Specific permissions for this user.
    TokenRefresh:
      required:
        - refresh
      type: object
      properties:
        refresh:
          title: Refresh
          minLength: 1
          type: string
        access:
          title: Access
          minLength: 1
          type: string
          readOnly: true
    UserUpdate:
      required:
        - first_name
        - last_name
        - nickname
        - personal_information
      type: object
      properties:
        first_name:
          title: Имя пользователя
          maxLength: 100
          minLength: 1
          type: string
        last_name:
          title: Фамилия пользователя
          maxLength: 100
          minLength: 1
          type: string
        nickname:
          title: Прозвище пользователя
          maxLength: 100
          minLength: 1
          type: string
        personal_information:
          title: Информация о себе
          maxLength: 500
          minLength: 1
          type: string
  securitySchemes:
    Basic:
      type: http
      scheme: basic
x-original-swagger-version: '2.0'
