openapi: 3.0.3
info:
  title: Messenger's API Documentation
  version: '1.0.0'
servers:
  - url: http://localhost:8080
security:
  - Basic: []

paths:
  /register/code_verification:
    post:
      tags:
        - Registration
      operationId: checkPassCode
      summary: 'Проверка пароля (пользователя)'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodeVerification'
        '400':
          description: Bad Request
        default: # Обработка непредвиденных ошибок сервера
          description: Internal Server Error # Внутренняя ошибка сервера
  /register:
    post:
      tags:
        - Registration
      operationId: addUser
      summary: 'Регистрация нового пользователя'
      responses:
        '201':
          description: OK #пользователь создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized #пользователь не авторизован
        '400':
          description: Bad Request
        default: # Обработка непредвиденных ошибок сервера
          description: Internal Server Error # Внутренняя ошибка сервера
  /register/send_message_to_support:
    post:
      tags:
        - Registration
      operationId: sendMessageToSupport
      summary: 'Отправка сообщения в поддержку'
      responses:
        '201':
          description: OK #сообщение .... создано? отправлено?
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendMassageToSuport'
        '401':
          description: Unauthorized #пользователь не авторизован
        '400':
          description: Bad Request
        default: # Обработка непредвиденных ошибок сервера
          description: Internal Server Error # Внутренняя ошибка сервера

components:
  securitySchemes:
    Basic:
      #apiKey, http, oauth2, openIdConnect
      type: http
      scheme: basic

  schemas:

    User:
      required:
        - phone
        - firstName
        - nickname
      type: object
      properties:
        phone:
          type: string
          pattern: '^\d{10}$'
          description: 'Номер телефона, 10 цифр'
        firstName:
          type: string
          maxLength: 64
          pattern: '^[a-zA-Zа-яА-Я\s]*$'
          description: 'имя пользователя, без цифр'
        lastName:
          type: string
          maxLength: 64
          pattern: '^[a-zA-Zа-яА-Я\s]*$'
          description: 'фамилия пользователя, без цифр'
          nullable: true
        nickname:
          type: string
          maxLength: 32
          minLength: 5
          pattern: '^(?!\s+$).*'
          description: 'никнейм пользователя, не может быть пустой строкой или состоять только из пробелов'
        about:
          type: string
          description: 'персональная информация пользователя'
          maxLength: 148
          nullable: true

    SendMassageToSuport:
      required:
        - phone
        - email
        - text
      type: object
      properties:
        phone:
          type: string
          pattern: '^\d{10}$'
          description: 'телефон пользователя'
        email:
          type: string
          pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
          description: 'почта пользователя. Валидный email, допустимые символы в локальной части - буквы, цифры, точки, подчеркивания, дефисы и знаки плюса. Обязательно присутствие символа @, затем нескольких символов, далее обязательной точки и снова символов.'
        text:
          type: string
          description: 'текст обращения'
          maxLength: 500
          minLength: 3

    CodeVerification:
      required:
        - phone
        - code
      type: object
      properties:
        phone:
          type: string
          pattern: '^\d{10}$'
          description: 'телефон пользователя'
        code:
          type: string
          pattern: '^\d{5}$'
          description: 'код-пароль с телефона, 5 цифр' #уточнить как будем получать

