openapi: 3.0.3
info:
  title: Messenger's API Documentation
  version: '1.0.0'
servers:
  - url: http://localhost:8080
security:
  - Basic: []

paths:
  /users/list:
    get:
      tags:
        - Users #- Пользователи

      operationId: getAllUsers
      summary: 'Получение списка всех пользователей'
      responses:
        '200':
          description: OK #пользователь авторизован, список получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized #пользователь не авторизован

        default: # Обработка непредвиденных ошибок сервера
          description: Internal Server Error # Внутренняя ошибка сервера

components:
  securitySchemes:
    Basic:
      #apiKey, http, oauth2, openIdConnect
      type: http
      scheme: basic

  schemas:
    User:
      required:
        - firstName
        - lastName
        - nickname
        - otpСode
        - personalInformation
        - phone

      type: object
      properties:

        id:
          type: integer
          format: int32
          description: 'id пользователя'
          readOnly: true

        lastLogin:
          type: integer
          format: date-time
          description: 'последняя авторизации в миллисекундах с 00:00:00 01.01.1970'
          nullable: true

        isSuperuser: #уточнить
          type: boolean
          description: 'является ли пользователь администратором'
          default: false

        email:
          type: string
          description: 'почта пользователя'
          maxLength: 64
          minLength: 4
          format: email

        isStaff:
          type: boolean
          description: 'является ли персоналом'
          default: false

        isActive:
          type: boolean
          description: 'активен ли пользователь'
          default: false

        dateJoined: #уточнить
          type: string
          description: 'дата присоединения' #уточнить
          format: date-time

        phone:
          type: string
          description: 'телефон пользователя'
          pattern: '\+7\s?\(?\d{3}\)?\s?\d{3}-?\d{2}-?\d{2}'

        firstName:
          type: string
          description: 'имя пользователя'
          maxLength: 64
          minLength: 2

        lastName:
          type: string
          description: 'фамилия пользователя'
          maxLength: 64
          minLength: 2

        nickname:
          type: string
          description: 'никнейм пользователя'
          maxLength: 32
          minLength: 1

        personal_information: #уточнить
          type: string
          description: 'персональная информация пользователя'
          maxLength: 500
          minLength: 1

        avatar:
          type: string
          description: 'аватар пользователя'
          #format: uri
          nullable: true

        is_verified:
          type: boolean
          description: 'верифицирован ли пользователь'
          default: false

        otpСode:
          type: string
          description: 'отп код пользователя'
          maxLength: 5
          nullable: false