server:
  port: 8080
spring:
  application:
    name: Messenger
  profiles:
    active: ${MSG_PROFILE:develop}
  #Database
  datasource:
    url: ${MSG_DB_URL:jdbc:postgresql://localhost:5432/messenger_db}
    username: ${MSG_DB_USERNAME:messenger_admin}
    password: ${MSG_DB_PASSWORD:R0t4@dm1n}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  data:
    mongodb:
      uri: ${MONGO_DB_URL:mongodb://admin:password@localhost:27017/filedb?authSource=admin}
  rabbitmq:
    host : localhost
    port : 5672
    username : user
    password : password
#Logging
logging:
  level:
    root: error
    web: error
    sql: error
    ru:
      salfa:
        messenger: debug
#OTP
otp:
  length: 5
  expiration: 300000
  number-of-attempts: 3
  interval-for-blocking: 1800000
  duration-of-blocking: 86400000
  send-sms: ${MSG_SEND_SMS:false}
#JWT
jwt:
  access-token-secret: 1daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb11
  access-token-expiration: 300000
  refresh-token-secret: 2daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb11
  refresh-token-expiration: 2592000000
#SMS
sms:
  username: ${MSG_SMS_USER:max.khrapatiy@gmail.com}
  password: ${MSG_SMS_PWD:gXGnCgVP0dTUOoBwGRV3guO1xgn_7_kO}
  title: ${MSG_SMS_TITLE:SMSAero}
#Websocket
websocket:
  endpoint: /api/v1/ws/chat
  textMessageSizeLimit: 104857600
springdoc:
  api-docs:
    path: /v3/api-docs  # Путь для API-документации
  swagger-ui:
    url: /openapi.yaml # Путь к вашему файлу OpenAPI


