-- Таблица для хранения "тикетов".
CREATE TABLE IF NOT EXISTS tickets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY     NOT NULL,
    phone               VARCHAR(16)                                 NOT NULL,
    email               VARCHAR(64)                                 NOT NULL,
    created             TIMESTAMP WITH TIME ZONE DEFAULT NOW()      NOT NULL,
    modified            TIMESTAMP WITH TIME ZONE,
    ticket_text         TEXT,
    status              INTEGER,
    CONSTRAINT pk_tickets PRIMARY KEY (id)
);
COMMENT ON TABLE tickets IS 'Список "тикетов".';
COMMENT ON COLUMN tickets.id IS 'Идентификатор записи в таблице.';
COMMENT ON COLUMN tickets.phone IS 'Номер мобильного телефона пользователя.';
COMMENT ON COLUMN tickets.email IS 'Адрес электронной почты пользователя.';
COMMENT ON COLUMN tickets.created IS 'Дата создания "тикета".';
COMMENT ON COLUMN tickets.modified IS 'Дата последнего редактирования "тикета".';
COMMENT ON COLUMN tickets.ticket_text IS 'Текст "тикета".';
COMMENT ON COLUMN tickets.status IS 'Статус "тикета".';